name: Build and deploy frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

  workflow_dispatch:


env:
  AZURE_WEBAPP_NAME: coriatodo-frontend-webapp
  NODE_VERSION: '18.x'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build
        # npm run test

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: coriatodo-app
        path: .

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: coriatodo-app

      # Login to Azure via Service Connection 
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZ_CREDS }}
        enable-AzPSSession: true
          
      # Deploy to Azure Web apps
    - name: 'Run Azure webapp deploy action using publish profile credentials'
      uses: azure/webapps-deploy@v2
      with: 
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
