name: CI Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'deployment/infrastructure/**.bicep'
  

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest
    steps:
      - run: echo "Starting..."
      - run: az login
