name: CI Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - 'deployment/infrastructure/**.bicep'
  

jobs:
  test:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting..."
      - run: az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }} --tenant ${{ secrets.AZ_TENANTID }}
      - run: az deployment group create -g ${{ secrets.AZ_TARGET_RG }} -f ${{GITHUB_WORKSPACE}}/deployment/infrastructure/backend.bicep -c
      
