name: CI Pipeline

on:
  workflow_dispatch:
    inputs:
      action_request:
        type: choice
        description: Action
        options:
        - Create
        - Destroy
        - Sing
  push:
    paths:
      - 'deploy/infra/**.bicep'
  

jobs:
  infra-work:
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/azure-cli:latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Starting..."
      - run: az login -u ${{ secrets.AZ_USERNAME }} -p ${{ secrets.AZ_PASSWORD }} --tenant ${{ secrets.AZ_TENANTID }}
      - name: Create Infra
        if: ${{ github.event.inputs.action_request == 'Create' || github.event.inputs.action_request == '' }}
        id: create-infra
        run: az deployment group create -g ${{ secrets.AZ_TARGET_RG }} -f ./deploy/infra/backend.bicep --parameters administratorLogin=${{ secrets.AZ_POSTGRES_USERNAME }} administratorLoginPassword=${{ secrets.AZ_POSTGRES_PASSWORD }}
      - name: Delete Infra
        if: ${{ github.event.inputs.action_request == 'Destroy' }}
        id: delete-infra
        run: az deployment group create -g ${{ secrets.AZ_TARGET_RG }} -f ./deploy/infra/backend-empty.bicep --mode complete
      - name: Sing about Infra
        if: ${{ github.event.inputs.action_request == 'Sing' }}
        id: sing-about-infra
        run: echo "La La La..."
